---
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: fileupload
          uri: http://fileupload:8082
          predicates:
            - Path=/fileupload
          filters:
            - SetPath=/file/upload
        - id: node-ws
          uri: ws://node:3001
          predicates:
            - Path=/node/ws/
          filters:
            - SetPath=/
        - id: node
          uri: http://node:3000
          predicates:
            - Path=/node/**
          filters:
            - RewritePath=/node(?<segment>/?.*), $\{segment}
        - id: python-ws
          uri: ws://python:5002
          predicates:
            - Path=/python/ws/
          filters:
            - SetPath=/
        - id: python
          uri: http://python:5001
          predicates:
            - Path=/python/**
          filters:
            - RewritePath=/python(?<segment>/?.*), $\{segment}
        - id: java-ws
          uri: ws://java:8081
          predicates:
            - Path=/java/ws/
          filters:
            - SetPath=/ws-java
          
        - id: kotlin-ws
          uri: ws://kotlin:9000
          predicates:
            - Path=/kotlin/ws/
          filters:
            - SetPath=/ws-kotlin
        - id: go-ws
          uri: ws://go:6000
          predicates:
            - Path=/go/ws/
          filters:
            - SetPath=/ws


