services:
  redis:
    image: redis:7.2.5-alpine
    hostname: redis
    ports:
    - '6379:6379'
  fileupload:
    image: ghcr.io/fullstack-e-learning/file-reader-fileupload:main
    user: root:root
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:rw
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
    ports:
      - '8080:8080'
  java:
    image: ghcr.io/fullstack-e-learning/file-reader-java:main
    user: root:root
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
    ports:
      - '8081:8081'
  kotlin:
    image: ghcr.io/fullstack-e-learning/file-reader-kotlin:main
    user: root:root
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
    ports:
      - '9000:9000'
  node:
    image: ghcr.io/fullstack-e-learning/file-reader-node:main
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
    ports:
      - '3000:3000'
      - '3001:3001'
  python:
    image: ghcr.io/fullstack-e-learning/file-reader-python:main
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
    ports:
      - '5000:5000'
      - '5001:5001'
  go:
    image: ghcr.io/fullstack-e-learning/file-reader-go:main
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
    ports:
      - '6000:6000'
volumes:
  file-storage:
    
