services:
  redis:
    image: redis:7.2.5-alpine
    hostname: redis
    ports:
    - '6379:6379'
  fileupload:
    image: ghcr.io/fullstack-e-learning/file-reader-fileupload:main
    restart: on-failure
    user: root:root
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:rw
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
      - server.port=8082
  java:
    image: ghcr.io/fullstack-e-learning/file-reader-java:main
    restart: on-failure
    user: root:root
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
  kotlin:
    image: ghcr.io/fullstack-e-learning/file-reader-kotlin:main
    restart: on-failure
    user: root:root
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
  node:
    image: ghcr.io/fullstack-e-learning/file-reader-node:main
    restart: on-failure
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
  python:
    image: ghcr.io/fullstack-e-learning/file-reader-python:main
    restart: on-failure
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
  go:
    image: ghcr.io/fullstack-e-learning/file-reader-go:main
    restart: on-failure
    depends_on:
      - redis
    volumes:
      - file-storage:/usr/data:r
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILE_LOOKUP_PATH=/usr/data
  gateway:
    image: ghcr.io/fullstack-e-learning/spring-cloud-gateway:main
    restart: on-failure
    depends_on:
      - fileupload
      - node
      - python
      - java
      - kotlin
      - go
    volumes:
      - ./gateway-config:/usr/data
    environment:
      - JAVA_TOOL_OPTIONS="-Dreactor.netty.http.server.accessLogEnabled=true"
      - spring.config.location=/usr/data/
    ports:
      - '8080:8080'
volumes:
  file-storage:
    
